# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    
    - name: Create .env for server
      working-directory: express_app
      run: |
        echo "$SERVER_ENV" > .env
      env:
        SERVER_ENV: ${{ secrets.Server_ENV }}

    - name: Install server dependencies
      working-directory: express_app
      run: npm install
      
    - name: Deploy and restart with PM2
      working-directory: express_app
      run: |
        if pm2 list | grep -q "ci-cd app"; then
          pm2 restart "ci-cd app"
        else
          pm2 start app.js --name "ci-cd app"
        fi


