name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
    
    - name: Create .env for server
      working-directory: ./server
      run: |
        echo "$SERVER_ENV" > .env
        echo "Environment file created:"
        cat .env
        echo $USER
        echo $PATH
        npm i -g pm2
      env:
        SERVER_ENV: ${{ secrets.Server_ENV }}

    - name: Install server dependencies
      working-directory: ./server
      run: npm install

    - name: Deploy and restart with PM2
      working-directory: ./server
      run: |
        if pm2 list | grep -q cicd; then
          echo "Restarting existing PM2 app..."
          pm2 restart cicd
        else
          echo "Starting new PM2 app..."
          pm2 start app.js --name cicd
        fi

    - name: Verify PM2 processes
      run: pm2 list
