name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Create .env for server
      working-directory: ./server
      run: |
        echo "$SERVER_ENV" > .env
        echo $USER
        echo $PATH
        npm i -g pm2
      env:
        SERVER_ENV: ${{ secrets.Server_ENV }}

    - name: Install server dependencies
      working-directory: ./server
      run: npm install
      
    - name: Deploy and restart with PM2
      working-directory: ./server
      run: |
        # If PM2 is running from the correct location
        if pm2 list | grep -q cicd; then
          pm2 restart cicd
        else
          # Start the app from the correct directory (root/action-runners)
          pm2 start /root/action-runners/server/app.js --name cicd
        fi
