name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
    
    - name: Move repository to the actions-runner directory
      run: |
        # Ensure the actions-runner directory exists before moving the repo
        sudo mkdir -p /root/actions-runner
        sudo mv /home/runner/work/express_app /root/actions-runner/
        # Change ownership and permissions for the /root/actions-runner directory and its contents
        sudo chown -R runner:runner /root/actions-runner
        sudo chmod -R 775 /root/actions-runner
        sudo chmod -R 755 /root/actions-runner/express_app

    - name: Set working directory to server and create .env file
      working-directory: /root/actions-runner/express_app/server
      run: |
        echo "$SERVER_ENV" > .env
        echo $USER
        echo $PATH
        npm i -g pm2
      env:
        SERVER_ENV: ${{ secrets.Server_ENV }}

    - name: Install server dependencies
      working-directory: /root/actions-runner/express_app/server
      run: npm install

    - name: Deploy and restart with PM2
      working-directory: /root/actions-runner/express_app/server
      run: |
        # If PM2 is running from the correct location
        if pm2 list | grep -q cicd; then
          pm2 restart cicd
        else
          # Start the app from the correct location
          pm2 start /root/actions-runner/express_app/server/app.js --name cicd
        fi
